version: "3.9"

services:

  db:
    image: postgres:16
    container_name: self_healing_postgres

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: healing_pipeline

    ports:
      - "5434:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .

    container_name: self_healing_app

    ports:
      - "8000:8000"

    depends_on:
      - db

    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/healing_pipeline

volumes:
  postgres_data: